channels:
- conda-forge
dependencies:
- jupyterlab
- nodejs
- widgetsnbextension
- bqplot
- matplotlib
- pandas
- python
- sympy
- pyyaml
- traittypes
- invoke
- protobuf
- requests
- whoosh
- arrow
- bokeh