#!/usr/bin/env bash

pip install .
jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build &&
jupyter labextension install bqplot --no-build &&
jupyter lab clean && jupyter lab build

